package bridge.tools;

import bridge.protocol.McpeBatch;

/**
 * Writes the set of item ids MC3DS knows to {@code src/main/resources/mc3ds-items.txt}, read out of
 * the game's own creative inventory in the M0 capture (ContainerSetContent, window 0x79).
 *
 * <p>Deriving it beats writing one by hand: it is the game's answer, not a guess about which Java
 * version MC3DS's content lines up with. Re-run it if the capture is ever replaced.
 *
 * <p>It is authoritative for ITEMS only. The same list badly under-reports blocks, because a block
 * placed from an item — water, doors, cake, crops, beds — never appears in the creative menu.
 */
public final class DumpMc3dsItems {

    public static void main(String[] args) throws Exception {
        byte[] batch;
        try (java.io.InputStream in = DumpMc3dsItems.class.getResourceAsStream("/spawn_batch.bin")) {
            batch = in.readAllBytes();
        }
        byte[] creative = null;
        for (byte[] p : McpeBatch.inflate(batch)) {
            if ((p[0] & 0xFF) == 0x34 && p.length > 1000) creative = p;
        }
        if (creative == null) throw new AssertionError("no creative ContainerSetContent in the capture");

        java.util.TreeSet<Integer> ids = new java.util.TreeSet<>();
        int[] at = {2};
        long unique = varlong(creative, at);
        int count = (int) varlong(creative, at);
        for (int i = 0; i < count; i++) {
            int id = zigzag((int) varlong(creative, at));
            if (id == 0) continue;                       // empty slot: a single zero byte
            varlong(creative, at);                       // aux
            varlong(creative, at);                       // constant 9
            varlong(creative, at);                       // constant 0
            at[0] += 4;
            ids.add(id);
        }
        StringBuilder sb = new StringBuilder(
                "# Item ids MC3DS knows, from the creative inventory in the M0 capture.\n"
              + "# Generated by bridge.tools.DumpMc3dsItems — do not edit by hand.\n"
              + "# ITEMS ONLY: blocks placed from an item (water, doors, crops) are absent here.\n");
        for (int id : ids) sb.append(id).append('\n');
        java.nio.file.Path out = java.nio.file.Path.of("src/main/resources/mc3ds-items.txt");
        java.nio.file.Files.writeString(out, sb.toString());
        System.out.println("wrote " + ids.size() + " ids to " + out + " (entity " + unique + ")");
    }

    private static long varlong(byte[] p, int[] at) {
        long r = 0; int s = 0;
        while (true) {
            int b = p[at[0]++] & 0xFF;
            r |= (long) (b & 0x7F) << s; s += 7;
            if ((b & 0x80) == 0) return r;
        }
    }

    private static int zigzag(int v) { return (v >>> 1) ^ -(v & 1); }
}
