package bridge.protocol;

/**
 * Which item ids MC3DS can show, and what to put in place of the ones it cannot.
 *
 * <p>The set is read from {@code mc3ds-items.txt}, generated by {@link bridge.tools.DumpMc3dsItems}
 * from the game's own creative inventory in the M0 capture — the game's answer rather than a guess
 * about which Java version its content lines up with. It even includes a couple of negative ids,
 * which no hand-written table would have thought to contain.
 *
 * <p>Substitution is purely cosmetic and costs nothing functionally: the bridge relays the player's
 * HOTBAR SLOT to the bot, not the item id, and the server acts on whatever the bot is really
 * holding. So a stack shown on the 3DS as stone can still behave as whatever it actually is.
 *
 * <p>This is authoritative for items only. It badly under-reports blocks — anything placed from an
 * item, so water, doors, cake, crops and beds, never appears in a creative menu — so it must not be
 * used to decide what a chunk may contain.
 */
public final class Mc3dsItems {


    /** Stand-ins, both confirmed present in the game's own list. */
    private static final int UNKNOWN_BLOCK = 1;    // stone
    private static final int UNKNOWN_ITEM = 280;   // stick

    /** The lowest id that is an item rather than a placeable block. */
    private static final int FIRST_ITEM_ID = 256;

    private static final java.util.logging.Logger log =
            java.util.logging.Logger.getLogger("bridge.items");
    private static final java.util.Set<Integer> reported =
            java.util.concurrent.ConcurrentHashMap.newKeySet();

    /** Declared after the logger on purpose: load() uses it, and static fields run in order. */
    private static final java.util.Set<Integer> KNOWN = load();

    private Mc3dsItems() {}

    private static java.util.Set<Integer> load() {
        java.util.Set<Integer> ids = new java.util.HashSet<>();
        try (java.io.InputStream in = Mc3dsItems.class.getResourceAsStream("/mc3ds-items.txt")) {
            if (in == null) {
                log.warning("mc3ds-items.txt missing — every item will be passed through unchanged");
                return ids;
            }
            for (String line : new String(in.readAllBytes(),
                    java.nio.charset.StandardCharsets.US_ASCII).split("\n")) {
                line = line.trim();
                if (!line.isEmpty() && !line.startsWith("#")) ids.add(Integer.parseInt(line));
            }
        } catch (Exception e) {
            log.warning("could not read mc3ds-items.txt: " + e);
        }
        log.info("MC3DS knows " + ids.size() + " item ids");
        return ids;
    }

    public static boolean known(int id) { return id == 0 || KNOWN.contains(id); }

    /** The id to show on the 3DS for a Java item: itself when it exists there, a stand-in if not. */
    public static int substitute(int id) {
        if (known(id)) return id;
        int stand = id < FIRST_ITEM_ID ? UNKNOWN_BLOCK : UNKNOWN_ITEM;
        if (reported.add(id)) {
            log.info("item " + id + " does not exist on the 3DS; showing " + stand
                    + " instead (it still behaves as item " + id + ", since the server acts on what"
                    + " the bot holds)");
        }
        return stand;
    }
}
